### ISSUE TITLE
共享文件夹无法使用

### ISSUE THREAD

**Issue by sudo-000** [Poempoat/LimboEmulatorPlus#1]
共享文件夹无法使用，保存设置后再读取又变成none。
不在虚拟机列表中选择none再选回来保存设置直接按开机也没用。
希望能修复一下，谢谢。

**Comment by Poempoat** [comment]
共享文件夹尚未完全实装，计划在2.0.4版本修复。

**Comment by sudo-000** [comment]
都2.0.5了共享文件夹怎么还没好啊？
还准备修不？
不准备修建议速速把那选项去掉。别留在那逼强迫症了！
